from app.ai.client import _parse_json
from app.ai.factory import complete_with_fallback
from app.config import settings
from app.dto.news import VerifyRequest, VerifyResponse

LOW_CONFIDENCE_THRESHOLD = 70

# {platform_context} is injected at call time from settings.AI_PLATFORM_CONTEXT.
# This keeps the prompt free of hardcoded deployment references so the same
# service works for Singapore, Giggle Academy, or any other operator.
_VERIFY_SYSTEM = """You are a fact-checking assistant for {platform_context}.
Your role is to assess whether a piece of content (a URL, message, or claim) is legitimate, suspicious, \
a scam, or misinformation.

Be honest about uncertainty. If the content is too vague or lacks enough detail for assessment, \
return verdict "insufficient_information".

Always respond ONLY with valid JSON matching the exact schema. No markdown, no extra text."""

_VERIFY_USER = """Assess the following content for potential online harms:

Content:
{content}

Return JSON with this exact schema:
{{
  "verdict": "legitimate" | "suspicious" | "scam" | "misinformation" | "insufficient_information",
  "confidence": <integer 0-100>,
  "red_flags": ["flag 1", "flag 2"],
  "recommendation": "one clear sentence on what the user should do",
  "reasoning": "2-3 sentences explaining your assessment"
}}

Rules:
- verdict must be exactly one of the five values above.
- confidence reflects how certain you are (0 = no idea, 100 = certain).
- If confidence < 70, still return a verdict but flag that it is uncertain.
- If content is too vague (e.g. just "is this real?" with no actual content to assess), \
  return verdict "insufficient_information" with confidence 0 and an empty red_flags list.
- red_flags should list specific signals that informed your verdict (empty list if none).
- recommendation must be actionable and concise.
- Never fabricate facts. If you cannot verify a claim, say so in reasoning."""

_DISCLAIMER_HIGH = (
    "This assessment is generated by AI and is for informational purposes only. "
    "Always verify important claims through trusted sources."
)

_DISCLAIMER_LOW = (
    "⚠️ Low confidence: This assessment is uncertain due to limited or ambiguous content. "
    "Do not rely on this verdict alone — cross-check with trusted sources before acting."
)

_DISCLAIMER_INSUFFICIENT = (
    "Please paste the actual suspicious content (URL, message text, or claim) "
    "so it can be assessed properly."
)

VALID_VERDICTS = {
    "legitimate", "suspicious", "scam", "misinformation", "insufficient_information"
}


async def verify_content(payload: VerifyRequest) -> VerifyResponse:
    raw = await complete_with_fallback(
        system=_VERIFY_SYSTEM.format(platform_context=settings.AI_PLATFORM_CONTEXT),
        user=_VERIFY_USER.format(content=payload.content),
        max_tokens=512,
    )

    data = _parse_json(raw, "verify_content")

    verdict = data.get("verdict", "insufficient_information")
    if verdict not in VALID_VERDICTS:
        verdict = "insufficient_information"

    confidence = int(data.get("confidence", 0))
    confidence = max(0, min(100, confidence))

    is_low_confidence = confidence < LOW_CONFIDENCE_THRESHOLD

    if verdict == "insufficient_information":
        disclaimer = _DISCLAIMER_INSUFFICIENT
    elif is_low_confidence:
        disclaimer = _DISCLAIMER_LOW
    else:
        disclaimer = _DISCLAIMER_HIGH

    return VerifyResponse(
        verdict=verdict,
        confidence=confidence,
        is_low_confidence=is_low_confidence,
        red_flags=data.get("red_flags", []),
        recommendation=data.get("recommendation", "Please verify this content manually."),
        disclaimer=disclaimer,
    )
